[package]
name = "si-tweak"
version = "0.1.0"
edition = "2021"


[dependencies]
config = "0.15.8"
rusqlite = { version = "0.33.0", features = ["bundled"] }
serde = { version = "1.0", features = ["derive"] } 
anyhow = "1.0"
serde_yaml = "0.9"
